version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Build Started
      - java -version
      - mvn -version

  build:
    commands:
      - mvn clean package

  post_build:
    commands:
      - echo Build Completed

artifacts:
  files:
    - target/*.jar
    - Procfile

cache:
  paths:
    - '/root/.m2/**/*'
